import BazelRemoteAPI

typealias ContentAddressableStorageProvider = Build_Bazel_Remote_Execution_V2_ContentAddressableStorageProvider

typealias FindMissingBlobsResponse = Build_Bazel_Remote_Execution_V2_FindMissingBlobsResponse
