import BazelRemoteAPI


typealias Directory = Build_Bazel_Remote_Execution_V2_Directory
typealias DirectoryNode = Build_Bazel_Remote_Execution_V2_DirectoryNode
typealias FileNode = Build_Bazel_Remote_Execution_V2_FileNode
typealias SymlinkNode = Build_Bazel_Remote_Execution_V2_SymlinkNode
typealias NodeProperties = Build_Bazel_Remote_Execution_V2_NodeProperties
typealias Digest = Build_Bazel_Remote_Execution_V2_Digest


typealias OutputFile = Build_Bazel_Remote_Execution_V2_OutputFile
typealias OutputSymlink = Build_Bazel_Remote_Execution_V2_OutputSymlink
