import SFBRBazelRemoteAPI

typealias ReadRequest = Google_Bytestream_ReadRequest
typealias ReadResponse = Google_Bytestream_ReadResponse
typealias WriteResponse = Google_Bytestream_WriteResponse
typealias WriteRequest = Google_Bytestream_WriteRequest
typealias QueryWriteStatusRequest = Google_Bytestream_QueryWriteStatusRequest
typealias QueryWriteStatusResponse = Google_Bytestream_QueryWriteStatusResponse
