import SFBRBazelRemoteAPI

typealias ServerCapabilities = Build_Bazel_Remote_Execution_V2_ServerCapabilities
typealias ExecutionCapabilities = Build_Bazel_Remote_Execution_V2_ExecutionCapabilities
typealias CacheCapabilities = Build_Bazel_Remote_Execution_V2_CacheCapabilities
typealias SymlinkAbsolutePathStrategy = Build_Bazel_Remote_Execution_V2_SymlinkAbsolutePathStrategy
typealias ActionCacheUpdateCapabilities = Build_Bazel_Remote_Execution_V2_ActionCacheUpdateCapabilities
typealias PriorityCapabilities = Build_Bazel_Remote_Execution_V2_PriorityCapabilities
typealias GetCapabilitiesRequest = Build_Bazel_Remote_Execution_V2_GetCapabilitiesRequest
